import { HeartIcon } from "@/sanity/lib/icons";
import { defineField, defineType } from "sanity";

export default defineType({
  name: "fiberArtsClub",
  title: "GNSHS Fiber Arts Club",
  type: "document",
  icon: HeartIcon,
  groups: [
    { name: "content", title: "Content", default: true },
    { name: "activities", title: "Activities section" },
    { name: "community", title: "Community projects section" },
    { name: "gallery", title: "Gallery" },
    { name: "seo", title: "SEO" },
  ],
  fields: [
    defineField({
      name: "heroEyebrow",
      title: "Header caption",
      description: "The small label shown above the page title.",
      type: "string",
      group: "content",
      initialValue: "Where it all started",
    }),
    defineField({
      name: "title",
      title: "Page title",
      type: "string",
      group: "content",
      initialValue: "GNSHS Fiber Arts Club",
    }),
    defineField({
      name: "mission",
      title: "Club mission",
      type: "text",
      rows: 3,
      group: "content",
    }),
    defineField({
      name: "ctaLabel",
      title: "Header button label",
      type: "string",
      group: "content",
      initialValue: "Get involved",
    }),
    defineField({
      name: "description",
      title: "Description",
      description: "Explain the club and its connection to Leap & Loop.",
      type: "array",
      of: [{ type: "block" }],
      group: "content",
    }),
    defineField({
      name: "heroImage",
      title: "Header image",
      type: "imageWithAlt",
      group: "content",
    }),
    defineField({
      name: "activitiesEyebrow",
      title: "Activities section caption",
      type: "string",
      group: "activities",
      initialValue: "What we do",
    }),
    defineField({
      name: "activitiesTitle",
      title: "Activities section heading",
      type: "string",
      group: "activities",
      initialValue: "Club activities",
    }),
    defineField({
      name: "activities",
      title: "Activities",
      type: "array",
      of: [{ type: "activityItem" }],
      group: "activities",
    }),
    defineField({
      name: "communityProjectsEyebrow",
      title: "Community projects section caption",
      type: "string",
      group: "community",
      initialValue: "Giving back",
    }),
    defineField({
      name: "communityProjectsTitle",
      title: "Community projects section heading",
      type: "string",
      group: "community",
      initialValue: "Community service projects",
    }),
    defineField({
      name: "communityProjects",
      title: "Community service projects",
      type: "array",
      of: [{ type: "galleryHighlight" }],
      group: "community",
    }),
    defineField({
      name: "galleryEyebrow",
      title: "Gallery section caption",
      type: "string",
      group: "gallery",
      initialValue: "Gallery",
    }),
    defineField({
      name: "galleryTitle",
      title: "Gallery section heading",
      type: "string",
      group: "gallery",
      initialValue: "From the club",
    }),
    defineField({
      name: "gallery",
      title: "Gallery",
      type: "array",
      of: [{ type: "imageWithAlt" }],
      group: "gallery",
    }),
    defineField({
      name: "seo",
      title: "SEO",
      type: "seo",
      group: "seo",
    }),
  ],
  preview: {
    select: { title: "title", media: "heroImage.image" },
    prepare({ title, media }) {
      return { title: title || "GNSHS Fiber Arts Club", media };
    },
  },
});
